[package]
name = "xplm-sys"
version = "0.1.2"
authors = ["Sam Crow <samcrow@uw.edu>"]
description = "Bindings for the X-Plane plugin SDK version 2.1"
repository = "https://github.com/samcrow/xplm-sys"
readme = "README.md"
keywords = ["X-Plane", "plugin"]
license = "MIT"

build = "link.rs"

[dependencies]
libc = "^0.2"
