[package]
name = "xplm210-sys"
version = "0.1.0"
authors = ["Sam Crow <samcrow@uw.edu>"]
description = "Bindings for the X-Plane plugin SDK version 2.1"
license = "MIT"

build = "link.rs"

[dependencies]
libc = "^0.2"
